spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "root"
    password: "root"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true
server:
  port: 8080

app:
  jwt:
    secret: 2JVPQzNKnRwTRYGXCywcLAassdad123123sdaassasadadasa==
    token:
      expiration:
        milis: 900000
  chatgpt:
    endpoint: https://api.openai.com/v1/chat/completions
    apiKey: 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
