spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "root"
    password: "root"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true
server:
  port: 8080

app:
  jwt:
    secret: "${JWT_SECRET}"
    token:
      expiration:
        milis: 200000000
  chatgpt:
    endpoint: https://api.openai.com/v1/chat/completions
    apiKey: "${OPEN_AI_API_KEY}"
